name: rosalive
description: Rosa Live Flutter Application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # UI
  google_fonts: ^6.1.0

  # Image slider
  carousel_slider: ^4.2.1

  # Image picker (profile upload)
  image_picker: ^1.0.7

  # Dropdown country
  country_picker: ^2.0.23

  # Local storage
  shared_preferences: ^2.2.2

  # UUID / random id
  uuid: ^4.2.1

  # Zego live streaming (future use)
  zego_uikit_prebuilt_live_streaming: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
